# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loads_consumption.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1137, 407)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 1121, 371))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ActivePower_W = QtGui.QLabel(self.groupBox)
        self.ActivePower_W.setGeometry(QtCore.QRect(120, 40, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ActivePower_W.setFont(font)
        self.ActivePower_W.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.ActivePower_W.setLineWidth(1)
        self.ActivePower_W.setAlignment(QtCore.Qt.AlignCenter)
        self.ActivePower_W.setObjectName(_fromUtf8("ActivePower_W"))
        self.Ld_5 = QtGui.QLabel(self.groupBox)
        self.Ld_5.setGeometry(QtCore.QRect(10, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ld_5.setFont(font)
        self.Ld_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(161, 241, 0);\n"
"border-color: rgb(0, 85, 0);"))
        self.Ld_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5.setObjectName(_fromUtf8("Ld_5"))
        self.Ld_2_AP = QtGui.QLabel(self.groupBox)
        self.Ld_2_AP.setGeometry(QtCore.QRect(120, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_AP.setFont(font)
        self.Ld_2_AP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_AP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_AP.setObjectName(_fromUtf8("Ld_2_AP"))
        self.Ld_1_AP = QtGui.QLabel(self.groupBox)
        self.Ld_1_AP.setGeometry(QtCore.QRect(120, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_AP.setFont(font)
        self.Ld_1_AP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_AP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_AP.setObjectName(_fromUtf8("Ld_1_AP"))
        self.Ld_4 = QtGui.QLabel(self.groupBox)
        self.Ld_4.setGeometry(QtCore.QRect(10, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ld_4.setFont(font)
        self.Ld_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(161, 241, 0);\n"
"border-color: rgb(0, 85, 0);"))
        self.Ld_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4.setObjectName(_fromUtf8("Ld_4"))
        self.Ld_1 = QtGui.QLabel(self.groupBox)
        self.Ld_1.setGeometry(QtCore.QRect(10, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ld_1.setFont(font)
        self.Ld_1.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(161, 241, 0);\n"
"border-color: rgb(0, 85, 0);"))
        self.Ld_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1.setObjectName(_fromUtf8("Ld_1"))
        self.Ld_3 = QtGui.QLabel(self.groupBox)
        self.Ld_3.setGeometry(QtCore.QRect(10, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ld_3.setFont(font)
        self.Ld_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(161, 241, 0);\n"
"border-color: rgb(0, 85, 0);"))
        self.Ld_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3.setObjectName(_fromUtf8("Ld_3"))
        self.Ld_2 = QtGui.QLabel(self.groupBox)
        self.Ld_2.setGeometry(QtCore.QRect(10, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Ld_2.setFont(font)
        self.Ld_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(161, 241, 0);\n"
"border-color: rgb(0, 85, 0);"))
        self.Ld_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2.setObjectName(_fromUtf8("Ld_2"))
        self.ReactivePower_VAR = QtGui.QLabel(self.groupBox)
        self.ReactivePower_VAR.setGeometry(QtCore.QRect(240, 40, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ReactivePower_VAR.setFont(font)
        self.ReactivePower_VAR.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.ReactivePower_VAR.setLineWidth(1)
        self.ReactivePower_VAR.setAlignment(QtCore.Qt.AlignCenter)
        self.ReactivePower_VAR.setObjectName(_fromUtf8("ReactivePower_VAR"))
        self.Ld_3_AP = QtGui.QLabel(self.groupBox)
        self.Ld_3_AP.setGeometry(QtCore.QRect(120, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_AP.setFont(font)
        self.Ld_3_AP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_AP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_AP.setObjectName(_fromUtf8("Ld_3_AP"))
        self.Ld_5_AP = QtGui.QLabel(self.groupBox)
        self.Ld_5_AP.setGeometry(QtCore.QRect(120, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_AP.setFont(font)
        self.Ld_5_AP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_AP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_AP.setObjectName(_fromUtf8("Ld_5_AP"))
        self.Ld_4_AP = QtGui.QLabel(self.groupBox)
        self.Ld_4_AP.setGeometry(QtCore.QRect(120, 260, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_AP.setFont(font)
        self.Ld_4_AP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_AP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_AP.setObjectName(_fromUtf8("Ld_4_AP"))
        self.Ld_4_RP = QtGui.QLabel(self.groupBox)
        self.Ld_4_RP.setGeometry(QtCore.QRect(240, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_RP.setFont(font)
        self.Ld_4_RP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_RP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_RP.setObjectName(_fromUtf8("Ld_4_RP"))
        self.Ld_1_RP = QtGui.QLabel(self.groupBox)
        self.Ld_1_RP.setGeometry(QtCore.QRect(240, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_RP.setFont(font)
        self.Ld_1_RP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_RP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_RP.setObjectName(_fromUtf8("Ld_1_RP"))
        self.Ld_3_RP = QtGui.QLabel(self.groupBox)
        self.Ld_3_RP.setGeometry(QtCore.QRect(240, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_RP.setFont(font)
        self.Ld_3_RP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_RP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_RP.setObjectName(_fromUtf8("Ld_3_RP"))
        self.Ld_5_RP = QtGui.QLabel(self.groupBox)
        self.Ld_5_RP.setGeometry(QtCore.QRect(240, 310, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_RP.setFont(font)
        self.Ld_5_RP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_RP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_RP.setObjectName(_fromUtf8("Ld_5_RP"))
        self.Ld_2_RP = QtGui.QLabel(self.groupBox)
        self.Ld_2_RP.setGeometry(QtCore.QRect(240, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_RP.setFont(font)
        self.Ld_2_RP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_RP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_RP.setObjectName(_fromUtf8("Ld_2_RP"))
        self.Ld_4_rmsCurrent = QtGui.QLabel(self.groupBox)
        self.Ld_4_rmsCurrent.setGeometry(QtCore.QRect(530, 260, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_rmsCurrent.setFont(font)
        self.Ld_4_rmsCurrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_rmsCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_rmsCurrent.setObjectName(_fromUtf8("Ld_4_rmsCurrent"))
        self.Ld_1_rmsCurrent = QtGui.QLabel(self.groupBox)
        self.Ld_1_rmsCurrent.setGeometry(QtCore.QRect(530, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_rmsCurrent.setFont(font)
        self.Ld_1_rmsCurrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_rmsCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_rmsCurrent.setObjectName(_fromUtf8("Ld_1_rmsCurrent"))
        self.Ld_3_rmsCurrent = QtGui.QLabel(self.groupBox)
        self.Ld_3_rmsCurrent.setGeometry(QtCore.QRect(530, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_rmsCurrent.setFont(font)
        self.Ld_3_rmsCurrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_rmsCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_rmsCurrent.setObjectName(_fromUtf8("Ld_3_rmsCurrent"))
        self.Ld_5_rmsCurrent = QtGui.QLabel(self.groupBox)
        self.Ld_5_rmsCurrent.setGeometry(QtCore.QRect(530, 310, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_rmsCurrent.setFont(font)
        self.Ld_5_rmsCurrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_rmsCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_rmsCurrent.setObjectName(_fromUtf8("Ld_5_rmsCurrent"))
        self.Ld_2_rmsCurrent = QtGui.QLabel(self.groupBox)
        self.Ld_2_rmsCurrent.setGeometry(QtCore.QRect(530, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_rmsCurrent.setFont(font)
        self.Ld_2_rmsCurrent.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_rmsCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_rmsCurrent.setObjectName(_fromUtf8("Ld_2_rmsCurrent"))
        self.RMS_Current_A = QtGui.QLabel(self.groupBox)
        self.RMS_Current_A.setGeometry(QtCore.QRect(530, 40, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RMS_Current_A.setFont(font)
        self.RMS_Current_A.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.RMS_Current_A.setLineWidth(1)
        self.RMS_Current_A.setAlignment(QtCore.Qt.AlignCenter)
        self.RMS_Current_A.setObjectName(_fromUtf8("RMS_Current_A"))
        self.BackButton = QtGui.QPushButton(self.groupBox)
        self.BackButton.setGeometry(QtCore.QRect(20, 10, 61, 51))
        self.BackButton.setStyleSheet(_fromUtf8("border-image: url(:/newPrefix/backbutton.png);"))
        self.BackButton.setText(_fromUtf8(""))
        self.BackButton.setObjectName(_fromUtf8("BackButton"))
        self.Ld_5_AppP = QtGui.QLabel(self.groupBox)
        self.Ld_5_AppP.setGeometry(QtCore.QRect(380, 310, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_AppP.setFont(font)
        self.Ld_5_AppP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_AppP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_AppP.setObjectName(_fromUtf8("Ld_5_AppP"))
        self.Ld_1_AppP = QtGui.QLabel(self.groupBox)
        self.Ld_1_AppP.setGeometry(QtCore.QRect(380, 110, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_AppP.setFont(font)
        self.Ld_1_AppP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_AppP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_AppP.setObjectName(_fromUtf8("Ld_1_AppP"))
        self.Ld_3_AppP = QtGui.QLabel(self.groupBox)
        self.Ld_3_AppP.setGeometry(QtCore.QRect(380, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_AppP.setFont(font)
        self.Ld_3_AppP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_AppP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_AppP.setObjectName(_fromUtf8("Ld_3_AppP"))
        self.App_Power_VA = QtGui.QLabel(self.groupBox)
        self.App_Power_VA.setGeometry(QtCore.QRect(380, 40, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.App_Power_VA.setFont(font)
        self.App_Power_VA.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.App_Power_VA.setLineWidth(1)
        self.App_Power_VA.setAlignment(QtCore.Qt.AlignCenter)
        self.App_Power_VA.setObjectName(_fromUtf8("App_Power_VA"))
        self.Ld_4_AppP = QtGui.QLabel(self.groupBox)
        self.Ld_4_AppP.setGeometry(QtCore.QRect(380, 260, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_AppP.setFont(font)
        self.Ld_4_AppP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_AppP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_AppP.setObjectName(_fromUtf8("Ld_4_AppP"))
        self.Ld_2_AppP = QtGui.QLabel(self.groupBox)
        self.Ld_2_AppP.setGeometry(QtCore.QRect(380, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_AppP.setFont(font)
        self.Ld_2_AppP.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_AppP.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_AppP.setObjectName(_fromUtf8("Ld_2_AppP"))
        self.Ld_5_PwrSrc_4 = QtGui.QLabel(self.groupBox)
        self.Ld_5_PwrSrc_4.setGeometry(QtCore.QRect(1020, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_PwrSrc_4.setFont(font)
        self.Ld_5_PwrSrc_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_PwrSrc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_PwrSrc_4.setObjectName(_fromUtf8("Ld_5_PwrSrc_4"))
        self.Ld_1_PwrSrc_4 = QtGui.QLabel(self.groupBox)
        self.Ld_1_PwrSrc_4.setGeometry(QtCore.QRect(1020, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_PwrSrc_4.setFont(font)
        self.Ld_1_PwrSrc_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_PwrSrc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_PwrSrc_4.setObjectName(_fromUtf8("Ld_1_PwrSrc_4"))
        self.Ld_3_PwrSrc_4 = QtGui.QLabel(self.groupBox)
        self.Ld_3_PwrSrc_4.setGeometry(QtCore.QRect(1020, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_PwrSrc_4.setFont(font)
        self.Ld_3_PwrSrc_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_PwrSrc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_PwrSrc_4.setObjectName(_fromUtf8("Ld_3_PwrSrc_4"))
        self.EDF_PV = QtGui.QLabel(self.groupBox)
        self.EDF_PV.setGeometry(QtCore.QRect(1020, 40, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EDF_PV.setFont(font)
        self.EDF_PV.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.EDF_PV.setLineWidth(1)
        self.EDF_PV.setAlignment(QtCore.Qt.AlignCenter)
        self.EDF_PV.setObjectName(_fromUtf8("EDF_PV"))
        self.Ld_4_PwrSrc_4 = QtGui.QLabel(self.groupBox)
        self.Ld_4_PwrSrc_4.setGeometry(QtCore.QRect(1020, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_PwrSrc_4.setFont(font)
        self.Ld_4_PwrSrc_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_PwrSrc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_PwrSrc_4.setObjectName(_fromUtf8("Ld_4_PwrSrc_4"))
        self.Ld_2_PwrSrc_4 = QtGui.QLabel(self.groupBox)
        self.Ld_2_PwrSrc_4.setGeometry(QtCore.QRect(1020, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_PwrSrc_4.setFont(font)
        self.Ld_2_PwrSrc_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_PwrSrc_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_PwrSrc_4.setObjectName(_fromUtf8("Ld_2_PwrSrc_4"))
        self.RMS_Voltage_V = QtGui.QLabel(self.groupBox)
        self.RMS_Voltage_V.setGeometry(QtCore.QRect(620, 40, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RMS_Voltage_V.setFont(font)
        self.RMS_Voltage_V.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.RMS_Voltage_V.setLineWidth(1)
        self.RMS_Voltage_V.setAlignment(QtCore.Qt.AlignCenter)
        self.RMS_Voltage_V.setObjectName(_fromUtf8("RMS_Voltage_V"))
        self.Ld_5_rmsVoltage = QtGui.QLabel(self.groupBox)
        self.Ld_5_rmsVoltage.setGeometry(QtCore.QRect(620, 310, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_rmsVoltage.setFont(font)
        self.Ld_5_rmsVoltage.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_rmsVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_rmsVoltage.setObjectName(_fromUtf8("Ld_5_rmsVoltage"))
        self.Ld_3_rmsVoltage = QtGui.QLabel(self.groupBox)
        self.Ld_3_rmsVoltage.setGeometry(QtCore.QRect(620, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_rmsVoltage.setFont(font)
        self.Ld_3_rmsVoltage.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_rmsVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_rmsVoltage.setObjectName(_fromUtf8("Ld_3_rmsVoltage"))
        self.Ld_1_rmsVoltage = QtGui.QLabel(self.groupBox)
        self.Ld_1_rmsVoltage.setGeometry(QtCore.QRect(620, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_rmsVoltage.setFont(font)
        self.Ld_1_rmsVoltage.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_rmsVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_rmsVoltage.setObjectName(_fromUtf8("Ld_1_rmsVoltage"))
        self.Ld_4_rmsVoltage = QtGui.QLabel(self.groupBox)
        self.Ld_4_rmsVoltage.setGeometry(QtCore.QRect(620, 260, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_rmsVoltage.setFont(font)
        self.Ld_4_rmsVoltage.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_rmsVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_rmsVoltage.setObjectName(_fromUtf8("Ld_4_rmsVoltage"))
        self.Ld_2_rmsVoltage = QtGui.QLabel(self.groupBox)
        self.Ld_2_rmsVoltage.setGeometry(QtCore.QRect(620, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_rmsVoltage.setFont(font)
        self.Ld_2_rmsVoltage.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_rmsVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_rmsVoltage.setObjectName(_fromUtf8("Ld_2_rmsVoltage"))
        self.Ld_5_PwrFact = QtGui.QLabel(self.groupBox)
        self.Ld_5_PwrFact.setGeometry(QtCore.QRect(710, 310, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_PwrFact.setFont(font)
        self.Ld_5_PwrFact.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_PwrFact.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_PwrFact.setObjectName(_fromUtf8("Ld_5_PwrFact"))
        self.Ld_1_PwrFact = QtGui.QLabel(self.groupBox)
        self.Ld_1_PwrFact.setGeometry(QtCore.QRect(710, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_PwrFact.setFont(font)
        self.Ld_1_PwrFact.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_PwrFact.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_PwrFact.setObjectName(_fromUtf8("Ld_1_PwrFact"))
        self.Ld_2_PwrFact = QtGui.QLabel(self.groupBox)
        self.Ld_2_PwrFact.setGeometry(QtCore.QRect(710, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_PwrFact.setFont(font)
        self.Ld_2_PwrFact.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_PwrFact.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_PwrFact.setObjectName(_fromUtf8("Ld_2_PwrFact"))
        self.Ld_3_PwrFact = QtGui.QLabel(self.groupBox)
        self.Ld_3_PwrFact.setGeometry(QtCore.QRect(710, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_PwrFact.setFont(font)
        self.Ld_3_PwrFact.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_PwrFact.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_PwrFact.setObjectName(_fromUtf8("Ld_3_PwrFact"))
        self.Ld_4_PwrFact = QtGui.QLabel(self.groupBox)
        self.Ld_4_PwrFact.setGeometry(QtCore.QRect(710, 260, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_PwrFact.setFont(font)
        self.Ld_4_PwrFact.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_PwrFact.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_PwrFact.setObjectName(_fromUtf8("Ld_4_PwrFact"))
        self.Power_Fact = QtGui.QLabel(self.groupBox)
        self.Power_Fact.setGeometry(QtCore.QRect(710, 40, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Power_Fact.setFont(font)
        self.Power_Fact.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.Power_Fact.setLineWidth(1)
        self.Power_Fact.setAlignment(QtCore.Qt.AlignCenter)
        self.Power_Fact.setObjectName(_fromUtf8("Power_Fact"))
        self.Frequency = QtGui.QLabel(self.groupBox)
        self.Frequency.setGeometry(QtCore.QRect(800, 40, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Frequency.setFont(font)
        self.Frequency.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.Frequency.setLineWidth(1)
        self.Frequency.setAlignment(QtCore.Qt.AlignCenter)
        self.Frequency.setObjectName(_fromUtf8("Frequency"))
        self.Ld_5_Freq = QtGui.QLabel(self.groupBox)
        self.Ld_5_Freq.setGeometry(QtCore.QRect(800, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_Freq.setFont(font)
        self.Ld_5_Freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_Freq.setObjectName(_fromUtf8("Ld_5_Freq"))
        self.Ld_2_Freq = QtGui.QLabel(self.groupBox)
        self.Ld_2_Freq.setGeometry(QtCore.QRect(800, 160, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_Freq.setFont(font)
        self.Ld_2_Freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_Freq.setObjectName(_fromUtf8("Ld_2_Freq"))
        self.Ld_4_Freq = QtGui.QLabel(self.groupBox)
        self.Ld_4_Freq.setGeometry(QtCore.QRect(800, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_Freq.setFont(font)
        self.Ld_4_Freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_Freq.setObjectName(_fromUtf8("Ld_4_Freq"))
        self.Ld_3_Freq = QtGui.QLabel(self.groupBox)
        self.Ld_3_Freq.setGeometry(QtCore.QRect(800, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_Freq.setFont(font)
        self.Ld_3_Freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_Freq.setObjectName(_fromUtf8("Ld_3_Freq"))
        self.Ld_1_Freq = QtGui.QLabel(self.groupBox)
        self.Ld_1_Freq.setGeometry(QtCore.QRect(800, 110, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_Freq.setFont(font)
        self.Ld_1_Freq.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_Freq.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_Freq.setObjectName(_fromUtf8("Ld_1_Freq"))
        self.Ld_5_Temp = QtGui.QLabel(self.groupBox)
        self.Ld_5_Temp.setGeometry(QtCore.QRect(900, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_5_Temp.setFont(font)
        self.Ld_5_Temp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_5_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_5_Temp.setObjectName(_fromUtf8("Ld_5_Temp"))
        self.Temperature = QtGui.QLabel(self.groupBox)
        self.Temperature.setGeometry(QtCore.QRect(900, 40, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Temperature.setFont(font)
        self.Temperature.setStyleSheet(_fromUtf8("background-color: rgb(255, 217, 0);"))
        self.Temperature.setLineWidth(1)
        self.Temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.Temperature.setObjectName(_fromUtf8("Temperature"))
        self.Ld_3_Temp = QtGui.QLabel(self.groupBox)
        self.Ld_3_Temp.setGeometry(QtCore.QRect(900, 210, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_3_Temp.setFont(font)
        self.Ld_3_Temp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_3_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_3_Temp.setObjectName(_fromUtf8("Ld_3_Temp"))
        self.Ld_1_Temp = QtGui.QLabel(self.groupBox)
        self.Ld_1_Temp.setGeometry(QtCore.QRect(900, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_1_Temp.setFont(font)
        self.Ld_1_Temp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_1_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_1_Temp.setObjectName(_fromUtf8("Ld_1_Temp"))
        self.Ld_2_Temp = QtGui.QLabel(self.groupBox)
        self.Ld_2_Temp.setGeometry(QtCore.QRect(900, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_2_Temp.setFont(font)
        self.Ld_2_Temp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_2_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_2_Temp.setObjectName(_fromUtf8("Ld_2_Temp"))
        self.Ld_4_Temp = QtGui.QLabel(self.groupBox)
        self.Ld_4_Temp.setGeometry(QtCore.QRect(900, 260, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Ld_4_Temp.setFont(font)
        self.Ld_4_Temp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.Ld_4_Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Ld_4_Temp.setObjectName(_fromUtf8("Ld_4_Temp"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.ActivePower_W.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Active power<br/>(W)</span></p></body></html>", None))
        self.Ld_5.setText(_translate("Form", "Load 5", None))
        self.Ld_2_AP.setText(_translate("Form", "0", None))
        self.Ld_1_AP.setText(_translate("Form", "0", None))
        self.Ld_4.setText(_translate("Form", "Load 4", None))
        self.Ld_1.setText(_translate("Form", "Load 1", None))
        self.Ld_3.setText(_translate("Form", "Load 3", None))
        self.Ld_2.setText(_translate("Form", "Load 2", None))
        self.ReactivePower_VAR.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Reactive power<br/>(VAR)</span></p></body></html>", None))
        self.Ld_3_AP.setText(_translate("Form", "0", None))
        self.Ld_5_AP.setText(_translate("Form", "0", None))
        self.Ld_4_AP.setText(_translate("Form", "0", None))
        self.Ld_4_RP.setText(_translate("Form", "0", None))
        self.Ld_1_RP.setText(_translate("Form", "0", None))
        self.Ld_3_RP.setText(_translate("Form", "0", None))
        self.Ld_5_RP.setText(_translate("Form", "0", None))
        self.Ld_2_RP.setText(_translate("Form", "0", None))
        self.Ld_4_rmsCurrent.setText(_translate("Form", "0", None))
        self.Ld_1_rmsCurrent.setText(_translate("Form", "0", None))
        self.Ld_3_rmsCurrent.setText(_translate("Form", "0", None))
        self.Ld_5_rmsCurrent.setText(_translate("Form", "0", None))
        self.Ld_2_rmsCurrent.setText(_translate("Form", "0", None))
        self.RMS_Current_A.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">RMS<br/>Current<br/>(A)</span></p></body></html>", None))
        self.Ld_5_AppP.setText(_translate("Form", "0", None))
        self.Ld_1_AppP.setText(_translate("Form", "0", None))
        self.Ld_3_AppP.setText(_translate("Form", "0", None))
        self.App_Power_VA.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Apparent Power<br/>(VA)</span></p></body></html>", None))
        self.Ld_4_AppP.setText(_translate("Form", "0", None))
        self.Ld_2_AppP.setText(_translate("Form", "0", None))
        self.Ld_5_PwrSrc_4.setText(_translate("Form", "EDF", None))
        self.Ld_1_PwrSrc_4.setText(_translate("Form", "EDF", None))
        self.Ld_3_PwrSrc_4.setText(_translate("Form", "EDF", None))
        self.EDF_PV.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">EDF / PV</span></p></body></html>", None))
        self.Ld_4_PwrSrc_4.setText(_translate("Form", "EDF", None))
        self.Ld_2_PwrSrc_4.setText(_translate("Form", "EDF", None))
        self.RMS_Voltage_V.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">RMS<br/>Voltage<br/>(V)</span></p></body></html>", None))
        self.Ld_5_rmsVoltage.setText(_translate("Form", "0", None))
        self.Ld_3_rmsVoltage.setText(_translate("Form", "0", None))
        self.Ld_1_rmsVoltage.setText(_translate("Form", "0", None))
        self.Ld_4_rmsVoltage.setText(_translate("Form", "0", None))
        self.Ld_2_rmsVoltage.setText(_translate("Form", "0", None))
        self.Ld_5_PwrFact.setText(_translate("Form", "0", None))
        self.Ld_1_PwrFact.setText(_translate("Form", "0", None))
        self.Ld_2_PwrFact.setText(_translate("Form", "0", None))
        self.Ld_3_PwrFact.setText(_translate("Form", "0", None))
        self.Ld_4_PwrFact.setText(_translate("Form", "0", None))
        self.Power_Fact.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Power<br/>Factor</span></p></body></html>", None))
        self.Frequency.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Frequency<br/>(Hz)</span></p></body></html>", None))
        self.Ld_5_Freq.setText(_translate("Form", "0", None))
        self.Ld_2_Freq.setText(_translate("Form", "0", None))
        self.Ld_4_Freq.setText(_translate("Form", "0", None))
        self.Ld_3_Freq.setText(_translate("Form", "0", None))
        self.Ld_1_Freq.setText(_translate("Form", "0", None))
        self.Ld_5_Temp.setText(_translate("Form", "0", None))
        self.Temperature.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Temperature<br/>(°C)</span></p></body></html>", None))
        self.Ld_3_Temp.setText(_translate("Form", "0", None))
        self.Ld_1_Temp.setText(_translate("Form", "0", None))
        self.Ld_2_Temp.setText(_translate("Form", "0", None))
        self.Ld_4_Temp.setText(_translate("Form", "0", None))

import xz_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

